import MovieDetail from './movie/MovieDetail'
import MovieForm from './movie/MovieForm'
import DirectorForm from './movie/DirectorForm'
import DirectorList from './movie/DirectorList'
import GenreForm from './movie/GenreForm'
import GenreList from './movie/GenreList'
import UsersList from './movie/UsersList'
import ActorForm from './movie/ActorForm'
import MovieList from './movie/MovieList'
import ActorList from './movie/ActorList'
import MovieListAux from './movie/MovieListAux'
import Registro from './movie/Registro'
import UserDetail from './movie/UserDetail'

export { MovieDetail,UserDetail, MovieForm, MovieList,UsersList,GenreForm, GenreList, DirectorForm, DirectorList,  MovieListAux,ActorList, ActorForm, Registro}
