import MovieDetail from './movie/MovieDetail'
import MovieForm from './movie/MovieForm'
import DirectorForm from './movie/DirectorForm'
import DirectorList from './movie/DirectorList'
import GenreForm from './movie/GenreForm'
import GenreList from './movie/GenreList'
import ActorForm from './movie/ActorForm'
import MovieList from './movie/MovieList'
import MovieListVistas from './movie/MovieListVistas'
import MovieListVistasVote from './movie/MovieListVistasVote'
import ActorList from './movie/ActorList'
import MovieListPendientes from './movie/MovieListPendientes'
import Registro from './movie/Registro'

export { MovieDetail, MovieForm, MovieList,GenreForm, GenreList, DirectorForm, DirectorList, MovieListVistas,MovieListVistasVote, MovieListPendientes,ActorList, ActorForm, Registro}
