spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:5432/asi
    username: asi
    password: asi
  jpa:
    # From https://vkuzel.com/spring-boot-jpa-hibernate-atomikos-postgresql-exception
    # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    # Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    # Creates and drops the database each run. Change to update/validate when needed.
    hibernate.ddl-auto: create
